=== Satish-Thapa/XML-GiftCardsNepal/catalog_20049029.xsd
<?xml version="1.0"?>
<!-- schema decleration -->
<!-- Flat Catalog Design -->
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">

    <!-- schema for the root element -->
    <xs:element name="store" >
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="logo"/>
                <xs:element ref="name"/>
                <xs:element ref="slogan"/>
                <xs:element ref="age_restriction"/>
                <xs:element ref="giftcard" minOccurs="2" maxOccurs="unbounded"/>
                <xs:element ref="acceptors"/>
                <xs:element ref="contact"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- ========================store================================ -->

    <!-- schema for store's logo -->
    <xs:element name="logo"/> 
       <!-- schema for store's name -->
    <xs:element name="name" type="xs:string"/>
       <!-- schema for store's slogan -->
    <xs:element name="slogan" type="xs:string"/>
     <!-- schema for store's age restriction -->
    <xs:element name="age_restriction">                             <!-- Age Restriction-->
        <xs:simpleType>
            <xs:restriction base="xs:integer">                      <!-- Integer Data Type-->
                <xs:minInclusive value="10"/>
                <xs:maxInclusive value="80"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <!-- schema for store's giftcard -->
    <xs:element name="giftcard">
        <xs:complexType>
            <xs:all>
                <xs:element ref="games" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="course" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="shop" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="resturant" minOccurs="0" maxOccurs="1
                "> </xs:element>
            </xs:all>
            <xs:attribute ref="type" use="required"></xs:attribute>
            <xs:attribute ref="payment" use="optional"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <!-- schema for store's acceptors -->
    <xs:element name="acceptors">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title" />
                <xs:element ref="game" />
                <xs:element ref="stores" />
                <xs:element ref="courses" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

   <!-- schema for store's contact -->
    <xs:element name="contact">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="detail"></xs:element>
                <xs:element ref="phone" minOccurs="2" maxOccurs="unbounded"></xs:element>
                <xs:element ref="add"></xs:element>
                <xs:element ref="services"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- =========================giftcard=============================== -->
    <!-- schema for giftcard's games -->
    <xs:element name="games">
        <xs:complexType>
            <xs:sequence maxOccurs="3">
                <xs:element ref="card" minOccurs="1" maxOccurs="3"/>
                <xs:element ref="line" minOccurs="1" maxOccurs="3"/>
            </xs:sequence>
            <xs:attribute ref="cateogary"/>
        </xs:complexType>
    </xs:element>
    <!-- schema for giftcard's course -->
    <xs:element name="course">
        <xs:complexType>
            <xs:sequence maxOccurs="2">
                <xs:element ref="card" minOccurs="1" maxOccurs="3"></xs:element>
                <xs:element ref="line" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
            <xs:attribute ref="cateogary"></xs:attribute>
        </xs:complexType>

    </xs:element>
    <!-- schema for giftcard's store -->
    <xs:element name="shop">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="card" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element ref="line" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
            <xs:attribute ref="cateogary"></xs:attribute>
        </xs:complexType>
    </xs:element>
      <!-- schema for giftcard's resturant -->
      <xs:element name="resturant">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="card" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element ref="line" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
            <xs:attribute ref="cateogary"></xs:attribute>
        </xs:complexType>
    </xs:element>
                            <!-- ==============games=================== -->
    <!-- schema for games's card -->
    
    <xs:element name="card">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gcard"></xs:element>
                <xs:element ref="info"></xs:element>
            </xs:sequence>
        </xs:complexType>

    </xs:element>
    <!-- schema for games'card -->

    <xs:element name="line"/>
    <!-- schema for card's gcard -->
    <xs:element name="gcard">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="genre"/>
                <xs:element ref="food" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="range" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="author" minOccurs="0" maxOccurs="1"/> 
                <xs:element ref="availability" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="currency" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="validity" minOccurs="0" maxOccurs="1" />
                <xs:element ref="cost" />
                <xs:element ref="code" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute ref="cateogary"/>
        </xs:complexType>
    </xs:element>

    <!-- schema for card's info -->
    <xs:element name="info">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="rating" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="number_of_buyers"/>
                <xs:element ref="discount" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="description"/>
                <xs:element ref="minimum_purchase" maxOccurs="1" minOccurs="0"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- =======================gcard=============================== -->
    <!-- schema for gcard's genre -->

    <xs:element name="genre">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="platform" minOccurs="0" maxOccurs="1"/>

            </xs:sequence>
          
            <xs:attribute ref="cateogary" use="required"></xs:attribute>


            
        </xs:complexType>
    </xs:element>
    <!-- schema for genre's platform -->
    <xs:element name="platform" type="xs:string"/>
    <!-- schema for gcard's currency -->
    <xs:element name="currency">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="UC"/>
                <xs:enumeration value="Diamonds"/>
                <xs:enumeration value="Points"/>

            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <!-- schema for gcard's validity -->
    <xs:element name="validity">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="type" use="optional"/>           
                    <xs:attribute ref="format" use="required"></xs:attribute>
                </xs:extension>
            </xs:simpleContent>
            
        </xs:complexType>
    </xs:element>
    <!-- schema for gcard's cost -->
    <xs:element name="cost">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="currency" use="required"/>
                    <xs:attribute ref="policy" use="optional"></xs:attribute>
                </xs:extension>
            </xs:simpleContent>
            
        </xs:complexType>
    </xs:element>
    <!-- schema for gcard's code -->
    <xs:element name="code" type="xs:ID"/>
    <!-- schema for gcard's author -->
    <xs:element name="author" type="xs:string"/>
    <!-- schema for gcard's  -->
    <xs:element name="availability" type="xs:string"/>
    <!-- schema for gcard's range -->
    <xs:element name="range" type="xs:string"/>
    <!-- schema for food -->
    <xs:element name="food" type="xs:string"></xs:element>
    <!-- ============================info======================================== -->
    <!-- schema for info's rating -->
    
    <xs:element name="rating">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="by" use="optional"></xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <!-- schema for info's number_of_buyers -->
    <xs:element name="number_of_buyers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="total"/>
                <xs:element ref="month" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- schema for number_of_buyers's total -->
    <xs:element name="total" type="xs:string"/>
    <xs:element name="month" type="xs:string" />

    <!-- schema for discount -->
    <xs:element name="discount">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="ratio" use="optional"/>
                    <xs:attribute ref="minimum_purchase" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
           
        </xs:complexType>
    </xs:element>
    <!-- schema for description -->
    <xs:element name="description" type="xs:string"/>
    <!-- schema for info's mimimum_purchase -->
    <xs:element name="minimum_purchase">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="currency" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <!-- ========================acceptors=================================== -->
   <xs:element name="title" type="xs:string"/>
    <xs:element name="game">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="platform_name" minOccurs="1" maxOccurs="3" ></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

   
    <xs:element name="stores">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="platform_name" minOccurs="1" maxOccurs="3"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="courses">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="platform_name"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="platform_name" >
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="form" use="optional"></xs:attribute>
                </xs:extension>
            </xs:simpleContent>
           
        </xs:complexType>
    </xs:element>
    <!-- ======================contact======================= -->
    <xs:element name="detail" type="xs:string"/>
    <xs:element name="phone">                                      
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="device" use="optional"></xs:attribute>
                </xs:extension>
            </xs:simpleContent>
            
        </xs:complexType>
    </xs:element>

    <xs:element name="add" type="xs:string"/>

    <xs:element name="services" type="xs:string"/>


    <!-- attrubutes -->
    <xs:attribute name="type" type="xs:string"/>
    <xs:attribute name="payment" type="xs:string"/>
    <xs:attribute name="format">                                         <!--Specific data format -->
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[D][D]-[M][M]-[Y][Y][Y][Y]"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="policy"></xs:attribute>
    <xs:attribute name="currency"></xs:attribute>
    <xs:attribute name="device">
        <xs:simpleType>                                               <!--Data Restriction-->
            <xs:restriction base="xs:string">
                <xs:enumeration value="TELEPHONE"/>
                <xs:enumeration value="MOBILE"/>

            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="form">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Digital"/>
                <xs:enumeration value="Physical"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="cateogary">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="games"/>
                <xs:enumeration value="course"/>
                <xs:enumeration value="store"/>
                <xs:enumeration value="resuturant"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="ratio"/>
    <xs:attribute name="minimum_purchase"/>
    <xs:attribute name="by"/>
</xs:schema>

=== Satish-Thapa/XML-GiftCardsNepal/catalog_20049029.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="catalog_20049029.css"?>
<!--
    Name: Satish Thapa
    College ID: np01cp4s210083
    London Met ID: 20049029
-->
<!-- This is an XML document about a giftcard shops which is completely made using xml , schema and CSS. -->
<store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="catalog_20049029.xsd">
    <logo></logo>
    <name>GiftCards Nepal</name>
    <slogan>More than just a card</slogan>
    <age_restriction>80</age_restriction>
    <giftcard type="DIGITAL" payment="Online">  <!-- Optional attribute-->
        <games cateogary="games">
            <card>
                <gcard cateogary="games">
                    <genre cateogary="games">Freefire</genre>
                    <currency>Diamonds</currency>
                    <validity type="Till_Date" format="DD-MM-YYYY">Valid Until: 06-06-2022 </validity>
                    <cost currency="Nepali_Rupees">COST: Rs.1000 </cost>
                    <code>CODE-G9876-7654-8768-9800</code>
                </gcard>
                <info>
                    <rating>Rating: EXCELLENT</rating>
                    <number_of_buyers>
                        <total>Total buyers: 511</total>
                        <month>Month buyers: 20</month> <!-- Optional Element-->
                    </number_of_buyers>
                    <discount ratio="Percentage">Discount: 20% </discount>
                    <description> Use the code and get Rs.950 worth of ingame diamonds purchase in Freefire </description>
                </info>
            </card>

            <line></line>

            <card>
                <gcard cateogary="games">
                    <genre cateogary="games">
                    PUBG
            </genre>
                    <currency>UC</currency>
                    <validity format="DD-MM-YYYY">Valid Until: 11-01-2022 </validity> <!-- Optional attribute-->
                    <cost currency="Nepali_Rupees">COST: Rs.1000 </cost>
                    <code>CODE-G2343-4567-6543-6788</code>
                </gcard>
                <info>
                    <rating>Rating: EXCILLENT</rating>
                    <number_of_buyers>
                        <total>Total buyers: 600</total>
                        <month>Monthly buyers: 100</month>
                    </number_of_buyers>
                    <discount> Discount: 20% </discount>  <!-- Optional attribute-->
                    <description> Use the code and get Rs.950 worth of ingame UC purchase in Pubg </description>
                </info>
            </card>
            <line></line>

            <card>
                <gcard cateogary="games">
                    <genre cateogary="games">
                        CS:GO
                        <platform>Steam</platform> <!-- Optional Element-->
                    </genre>
                    <currency>Points</currency>
                    <validity type="Till_Date" format="DD-MM-YYYY">Valid Until: 05-15-2022 </validity>
                    <cost currency="USD" policy="No_Return">COST: Rs. 1155 </cost>  <!-- Optional attribute-->
                    <code>CODE-G1234-5678-9101-1121</code>
                </gcard>
                <info>
                    <number_of_buyers>
                        <total>Total_buyers: 10</total>
                    </number_of_buyers>
                    <discount minimum_purchase="Two_Cards" ratio="Percentage">Discount: 20 </discount>
                    <description> Use the code and get Rs.1100 worth of ingame points purchase in Steam </description>
                </info>
            </card>
            <line></line>
        </games>


        <course cateogary="course">
            <card>
                <gcard cateogary="course">
                    <genre cateogary="course">
                    The Complete 2021 Flutter Development Bootcamp with Dart
            </genre>
                    <author>Author: Dr. Angela Yu</author> <!-- Optional Element-->
                    <availability>Availability: YES</availability> <!-- Optional Element-->
                    <validity type="Till_Date" format="DD-MM-YYYY">Valid Until: 08-23-2022 </validity>
                    <cost currency="Nepali_Rupees">COST: Rs.500 </cost>
                    <code >CODE-C3454-3456-7898-6754</code>        <!-- Optional attribute-->

                </gcard>
                <info>
                    <rating by="Students" >Rating: AVERAGE</rating> <!-- Optional Element-->
                    <number_of_buyers>
                        <total>Total_buyers: 10</total>
                    </number_of_buyers>
                    <description> Use the code and get this awesome course by Dr Angela Yu </description>
                </info>
            </card>
            <line></line>

            <card>
                <gcard cateogary="course">
                    <genre cateogary="course">
                    Learn Python: The Complete Python Programming Course
            </genre>
                    <!--  -->
                    <author>Author: Dr. Angela Yu</author>
                    <availability>Availablity: NO</availability>
                    <validity type="Till_Date" format="DD-MM-YYYY">Valid Until: 09-19-2022 </validity>
                    <cost currency="Nepali_Rupees">COST: Rs.500 </cost>
                    <code>CODE-C8797-0989-9999-0900</code>
                </gcard>
                <info>
                    <rating by="UDEMY">Rating: GOOD</rating>
                    <number_of_buyers>
                        <total>Total_buyers: 74</total>
                        <month>Monthly_buyers: 10</month>
                    </number_of_buyers>
                    <description> Use the code and get this awesome course by Dr Angela Yu </description>
                </info>
            </card>
            <line></line>
        </course>
    </giftcard>


    <giftcard type="PHYSICAL">
        <shop cateogary="store" >
            <card>
                <gcard cateogary="store">
                    <genre cateogary="store">
                    Bhat Bhateni
                    </genre>
                    <range>INSIDE VALLEY</range>       <!-- Optional Element-->
                    <validity type="Till_Date" format="DD-MM-YYYY">Valid Until: 10-09-2023 </validity>
                    <cost currency="Nepali_Rupees">COST: Rs.3000 </cost>

                </gcard>
                <info>
                    <rating>Rating: EXCILLENT</rating>
                    <number_of_buyers>
                        <total>Total_buyers: 1000</total>
                        <month>Monthly_buyers: 300</month>
                    </number_of_buyers>
                    <description> Buy the voucher and get a discount of Nrs.2500 on the total purchase of Nrs.5000</description>
                    <minimum_purchase currency="Nepali_Rupees">Minimun_purchase: Nrs.1000 </minimum_purchase>  <!-- Optional attribute-->
                </info>
            </card>
            <line></line>
        </shop>
        
        <resturant cateogary="resuturant" >
            <card>
                <gcard cateogary="resuturant">
                    <genre cateogary="resuturant">
                    Burger House and Crunchy Fried Chicken
            </genre>
                    <food>Voucher On: Any Liquors</food>  <!-- Optional Element-->
                    <validity type="Today_Only" format="DD-MM-YYYY">Valid Until: 11-09-2023 </validity>
                    <cost currency="Nepali_Rupees">COST: Rs.500 </cost>
                </gcard>
                <info>
                    <rating>Rating: EXCILLENT</rating>
                    <number_of_buyers>
                        <total>Total_buyers: 698</total>
                        <month>Monthly_buyers: 125</month>
                    </number_of_buyers>
                    <description> Buy the voucher and get a discount of Nrs.450 on the total purchase of Nrs.3000</description>
                    <minimum_purchase currency="Nepali_Rupees">Minimum Purchase Nrs.3000 </minimum_purchase>
                </info>
            </card>
            <line></line>
        </resturant>


    </giftcard>


    <acceptors >
        <title>Our Gift Card Acceptors</title>
        <game>
            <platform_name form="Digital">Pubg</platform_name>
            <platform_name form="Digital">CS:GO</platform_name>
            <platform_name form="Digital">FreeFire</platform_name>
        </game>
        <stores>
            <platform_name form="Physical">Bhat Bhateni</platform_name>
            <platform_name form="Physical">Burger House and Crunchy Fried Chicken</platform_name>

        </stores>
        <courses>
            <platform_name>UDEMY</platform_name>  <!-- Optional attribute-->
        </courses>

    </acceptors>
    <contact>
        <detail>Reach Out To Us !!</detail>
        <phone device="TELEPHONE">Phone 01-4991543</phone>
        <phone >9840724587</phone>     <!-- Optional attribute-->

        <add>Address: Jadibhuti Kathmandu</add>

        <services>
        We sell digital and physical giftcards for stores, games and online courses
        for reasonable price.
    </services>

    </contact>

</store>
